import { useEffect, useMemo, useState } from 'react';
import { ArrowDownLeft, ArrowLeft, ArrowRight, Bookmark, Check, ChevronRight, Clock3, Compass, Download, Feather, Flower2, Footprints, Leaf, MapPin, Menu, NotebookPen, Plus, ShieldCheck, Sparkles, Trash2, Wind, X } from 'lucide-react';
import { blankState, blindPrompts, fallback, readState, todayQuest, todayQuests, uid, writeState, type Capsule, type Note, type OutOfPlace, type Quest, type State } from '../data';

type Page='today'|'notes'|'capsules'|'blind'|'out'|'impact'|'settings';
const nav=[{id:'today',label:'Today',icon:Flower2},{id:'notes',label:'Field notes',icon:NotebookPen},{id:'capsules',label:'Time capsule',icon:Bookmark},{id:'blind',label:'Blind walk',icon:Compass},{id:'out',label:'Out of place',icon:Wind},{id:'impact',label:'Your impact',icon:Leaf}] as const;
const dateLabel=(value:string|number)=>new Intl.DateTimeFormat('en',{weekday:'short',month:'short',day:'numeric'}).format(new Date(value));
const timeLeft=(start:number,duration:number,now:number)=>Math.max(0,Math.ceil((duration*60000-(now-start))/60000));

export default function App(){
  const [data,setData]=useState<State>(()=>readState()); const [page,setPage]=useState<Page>('today'); const [duration,setDuration]=useState(15); const [modal,setModal]=useState(''); const [now,setNow]=useState(Date.now()); const [saving,setSaving]=useState(false); const [toast,setToast]=useState(''); const [selectedNote,setSelectedNote]=useState<Note|null>(null); const [photo,setPhoto]=useState('');
  const [answers,setAnswers]=useState<Record<string,string>>({}); const [capsuleDraft,setCapsuleDraft]=useState({title:'',note:'',context:''}); const [outDraft,setOutDraft]=useState({title:'',note:'',status:'Observed'}); const [revisitNote,setRevisitNote]=useState('');
  const quest=todayQuest(); const dailyQuests=todayQuests(); const todayLabel=new Intl.DateTimeFormat('en',{weekday:'long',month:'long',day:'numeric'}).format(new Date());
  useEffect(()=>{writeState(data)},[data]);
  useEffect(()=>{if(!data.active)return; const t=setInterval(()=>setNow(Date.now()),1000); return()=>clearInterval(t)},[data.active]);
  useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(''),3000);return()=>clearTimeout(t)}},[toast]);
  const set:React.Dispatch<React.SetStateAction<State>>=setData;
  const go=(p:Page)=>{setPage(p);window.scrollTo({top:0,behavior:'smooth'})};
  const begin=(mode='expedition',selectedQuest:Quest[]= [quest])=>{const id=uid();set({...data,active:{id,startedAt:Date.now(),duration,quests:selectedQuest,mode}});setNow(Date.now());setModal('')};
  const finish=()=>{if(!data.active)return; const active=data.active;set({...data,active:undefined,pendingNote:{expeditionId:active.id,duration:Math.max(1,Math.round((Date.now()-active.startedAt)/60000)),quests:active.quests}});setAnswers({});setPhoto('');setPage('today')};
  const saveNote=async()=>{
    if(!data.pendingNote)return; const pending=data.pendingNote; const userText=Object.values(answers).filter(Boolean).join('\n\n'); if(!userText.trim()&&!photo){setToast('Add a few words before saving your note.');return}
    setSaving(true); const note:Note={id:uid(),expeditionId:pending.expeditionId,createdAt:new Date().toISOString(),duration:pending.duration,quest:pending.quests,answers:{...answers},photos:photo?[photo]:[],reflection:fallback.reflection,pattern:fallback.pattern,tomorrowQuest:fallback.tomorrowQuest};
    // Persist the note first; model availability never controls journal creation.
    const saved={...data,notes:[note,...data.notes],pendingNote:undefined};set(saved);
    try{const response=await fetch('/api/reflect',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({expeditionId:pending.expeditionId,note:userText,duration:pending.duration,quests:pending.quests})});if(response.ok){const reflection=await response.json();set(s=>({...s,notes:s.notes.map(n=>n.expeditionId===pending.expeditionId?{...n,...reflection}:n),tomorrowQuest:reflection.tomorrowQuest}))}else throw new Error('');}catch{set(s=>({...s,tomorrowQuest:fallback.tomorrowQuest}))}
    setSaving(false);setModal('');setToast('Field note saved.');go('notes');
  };
  const updatePhoto=(file?:File)=>{if(!file)return;const reader=new FileReader();reader.onload=()=>setPhoto(String(reader.result));reader.readAsDataURL(file)};
  const downloadCard=(note:Note)=>{const quote=Object.values(note.answers).find(Boolean)||note.quest[0]?.description||'';const svg=makeShareCard(note,quote);const url=URL.createObjectURL(new Blob([svg],{type:'image/svg+xml'}));const link=document.createElement('a');link.href=url;link.download=`observe-field-note-${note.createdAt.slice(0,10)}.svg`;link.click();URL.revokeObjectURL(url);setToast('Your field-note card is ready to share.')};
  const saveCapsule=()=>{if(!capsuleDraft.title.trim()&&!capsuleDraft.note.trim()){setToast('Add a title or a note first.');return}const capsule:Capsule={id:uid(),...capsuleDraft,createdAt:new Date().toISOString(),photo:photo||undefined,revisits:[]};set({...data,capsules:[capsule,...data.capsules]});setCapsuleDraft({title:'',note:'',context:''});setPhoto('');setModal('');setToast('Saved for another day.')};
  const saveOut=()=>{if(!outDraft.title.trim()){setToast('Give this observation a title.');return}const item:OutOfPlace={id:uid(),...outDraft,createdAt:new Date().toISOString(),photo:photo||undefined};set({...data,outOfPlace:[item,...data.outOfPlace]});setOutDraft({title:'',note:'',status:'Observed'});setPhoto('');setModal('');setToast('Observation recorded.')};
  const addRevisit=(cap:Capsule)=>{if(!revisitNote.trim())return;set({...data,capsules:data.capsules.map(c=>c.id===cap.id?{...c,revisits:[...c.revisits,{date:new Date().toISOString(),note:revisitNote}]}:c)});setRevisitNote('');setModal('');setToast('Return visit added.')};
  const active=data.active; const remain=active?timeLeft(active.startedAt,active.duration,now):0;
  const totalMinutes=data.notes.reduce((sum,n)=>sum+n.duration,0); const daysOutside=Math.round(totalMinutes/60*10)/10;
  const categories=[['Expeditions completed',data.notes.length],['Time spent outside',`${daysOutside} hrs`],['Observations recorded',data.notes.length],['Places revisited',data.capsules.reduce((s,c)=>s+c.revisits.length,0)],['Field notes created',data.notes.length],['Safe care actions',data.outOfPlace.filter(o=>o.status==='Safely removed'||o.status==='Reported').length]] as const;
  const navAction=(p:Page)=>go(p);

  if(active) return <main className="active-screen"><div className="active-mark"><span className="brand-symbol"><Leaf size={20}/></span> OBSERVE</div><div className="active-content"><div className="eyebrow">{active.mode==='blind'?'BLIND WALK':'EXPEDITION IN PROGRESS'}</div><div className="timer">{String(remain).padStart(2,'0')}<span>min</span></div><p className="active-message">Your mission is saved.<br/><strong>Put your phone away.</strong><br/>See you when you're back.</p>{active.mode==='blind'&&<div className="active-prompt">{active.quests.map(q=><p key={q.title}>{q.title}</p>)}</div>}<div className="active-quest"><span className="eyebrow">A thought to carry</span><p>{active.quests[0]?.description}</p></div><button className="button button-outline" onClick={finish}><ArrowDownLeft size={17}/> I’m back</button></div><p className="active-foot">No GPS. No feed. Just you and the world outside.</p></main>;

  return <div className="app-shell"><aside className="sidebar"><a className="brand" onClick={()=>go('today')}><span className="brand-symbol"><Leaf size={19}/></span><span>OBSERVE<small>FIELD NOTES FOR EVERYWHERE</small></span></a><div className="sidebar-label">YOUR NOTEBOOK</div><nav>{nav.map(item=>{const Icon=item.icon;return <button key={item.id} className={`nav-item ${page===item.id?'selected':''}`} onClick={()=>navAction(item.id as Page)}><Icon size={17}/>{item.label}{item.id==='notes'&&data.notes.length>0&&<span className="nav-count">{data.notes.length}</span>}</button>})}</nav><div className="sidebar-bottom"><div className="privacy-note"><ShieldCheck size={15}/><span>Your notes stay on this device.</span></div><button className="nav-item" onClick={()=>go('settings')}><Menu size={17}/> Data & privacy</button><div className="sidebar-footer">A little more here than meets the eye.</div></div></aside>
  <header className="mobile-header"><button className="brand" onClick={()=>go('today')}><span className="brand-symbol"><Leaf size={19}/></span><span>OBSERVE</span></button><button className="icon-button" onClick={()=>go('settings')} aria-label="Data and privacy"><Menu size={20}/></button></header>
  <div className="mobile-nav">{nav.map(item=>{const Icon=item.icon;return <button aria-label={item.label} className={page===item.id?'selected':''} key={item.id} onClick={()=>go(item.id as Page)}><Icon size={18}/><span>{item.label==='Field notes'?'Notes':item.label==='Time capsule'?'Capsules':item.label==='Your impact'?'Impact':item.label==='Out of place'?'Out of place':'Today'}</span></button>})}</div>
  <main className="main-content">
    {page==='today'&&<><div className="today-top"><div><div className="eyebrow">{todayLabel.toUpperCase()}</div><h1>Good morning,<br/><em>curious one.</em></h1><p className="intro">You don't need to go to a forest to explore nature. There are entire ecosystems hiding in the cracks of your neighborhood.</p></div><span className="sun-mark">✳</span></div>
      {data.pendingNote&&<section className="welcome-back"><div><span className="eyebrow">WELCOME BACK</span><h2>What did you notice?</h2><p>Your walk is waiting in your notebook.</p></div><button className="button button-dark" onClick={()=>setModal('note')}>Write field note <ArrowRight size={16}/></button></section>}
      <section className="expedition-layout"><div className="today-quest"><div className="section-overline"><span className="eyebrow">TODAY’S EXPEDITION</span><span className="tiny-dot"/> <span className="eyebrow">{quest.category.toUpperCase()}</span></div><h2>{quest.title}</h2><p>{quest.description}</p><ul className="quest-list">{dailyQuests.slice(1).map((q,i)=><li key={q.title}><span>0{i+2}</span><div><b>{q.title}</b><small>{q.description}</small></div></li>)}</ul><div className="quest-meta"><span><Clock3 size={15}/> A small {duration}-minute wander</span><span className="no-photo-note"><ShieldCheck size={15}/> Leave the camera in your pocket</span></div><div className="duration-label">HOW LONG HAVE YOU GOT?</div><div className="duration-options">{[15,30,45].map(d=><button key={d} onClick={()=>setDuration(d)} className={duration===d?'chosen':''}>{d}<small>min</small></button>)}</div><button className="button button-dark start-button" onClick={()=>begin('expedition',dailyQuests)}><Footprints size={18}/> Start expedition <ArrowRight size={17}/></button><div className="tiny-exit">Your phone is the notebook, not the experience.</div></div><div className="meadow-art" aria-label="Illustration of neighborhood rooftops and flowers"><div className="art-sun"/><div className="art-hill hill-one"/><div className="art-hill hill-two"/><div className="art-house house-a"><i/><i/><b/></div><div className="art-house house-b"><i/><i/><b/></div><div className="art-window window-a"/><div className="art-flower flower-a"><i/><i/><i/><i/><b/></div><div className="art-flower flower-b"><i/><i/><i/><i/><b/></div><div className="art-stem"/><div className="art-label">A world in the everyday <span>✳</span></div></div></section>
      <section className="home-lower"><div className="home-lower-title"><div><span className="eyebrow">A FEW WAYS TO WANDER</span><h2>Choose your own noticing.</h2></div><button className="text-button" onClick={()=>go('blind')}>Explore all <ArrowRight size={15}/></button></div><div className="mode-strip"><button onClick={()=>{setDuration(15);go('blind')}}><span className="mode-icon sage"><Compass/></span><strong>Blind walk</strong><small>Let curiosity lead.</small><ChevronRight size={17}/></button><button onClick={()=>{setPage('out');setModal('out')}}><span className="mode-icon peach"><Wind/></span><strong>Out of place</strong><small>Notice what doesn't fit.</small><ChevronRight size={17}/></button><button onClick={()=>{setPage('capsules');setModal('capsule')}}><span className="mode-icon lilac"><Bookmark/></span><strong>Time capsule</strong><small>Leave a note for later.</small><ChevronRight size={17}/></button></div></section>
      <section className="home-last"><span className="eyebrow">A PAGE FROM YOUR NOTEBOOK</span>{data.notes[0]?<button className="last-note" onClick={()=>{setSelectedNote(data.notes[0]);setModal('note-detail')}}><span className="note-date">{dateLabel(data.notes[0].createdAt)}</span><strong>{Object.values(data.notes[0].answers).filter(Boolean)[0]||data.notes[0].quest[0]?.title}</strong><span className="text-button">Open note <ArrowRight size={15}/></span></button>:<p className="empty-line">Your first observation is still out there waiting.</p>}{data.tomorrowQuest&&<div className="tomorrow"><Sparkles size={17}/><span><b>For tomorrow</b><small>{data.tomorrowQuest.title} · {data.tomorrowQuest.description}</small></span></div>}</section></>}
    {page==='notes'&&<><PageHeader kicker="YOUR JOURNAL" title="Field notes" desc="A record of the things you stopped to notice."/><div className="journal-list">{data.notes.length===0?<Empty icon={<NotebookPen/>} title="Your pages are blank." text="That’s a good place to begin. Head outside, then come back and write what stayed with you." action="Start an expedition" onClick={()=>go('today')}/>:data.notes.map(note=><button className="journal-row" key={note.id} onClick={()=>{setSelectedNote(note);setModal('note-detail')}}><div className="journal-date">{dateLabel(note.createdAt)}</div><div className="journal-main"><span className="eyebrow">{note.quest[0]?.category?.toUpperCase()} · {note.duration} MIN OUTSIDE</span><strong>{Object.values(note.answers).filter(Boolean)[0]||note.quest[0]?.title||'A small observation'}</strong><p>{Object.values(note.answers).filter(Boolean)[0]?.slice(0,150)||note.quest[0]?.description}</p></div><ArrowRight size={17}/></button>)}</div></>}
    {page==='capsules'&&<><PageHeader kicker="A NOTE LEFT FOR LATER" title="Time capsules" desc="Save a place or a small detail. Come back when the world has had time to change." button="Save a capsule" onClick={()=>setModal('capsule')}/><div className="capsule-grid">{data.capsules.length===0?<Empty icon={<Bookmark/>} title="Nothing tucked away. Yet." text="Save a little detail for another day, and see what time does with it." action="Make a time capsule" onClick={()=>setModal('capsule')}/>:data.capsules.map(c=><article className="capsule-card" key={c.id}>{c.photo?<img src={c.photo}/>:<div className="capsule-art"><span>✳</span><span>✿</span><span>·</span></div>}<div className="capsule-copy"><span className="eyebrow">LEFT {dateLabel(c.createdAt).toUpperCase()}</span><h3>{c.title||'A place to remember'}</h3><p>{c.note}</p>{c.context&&<span className="context-line"><MapPin size={13}/>{c.context}</span>}{c.revisits.map((r,i)=><div className="revisit" key={i}><span className="eyebrow">RETURNED {dateLabel(r.date).toUpperCase()}</span><p>{r.note}</p></div>)}<button className="text-button" onClick={()=>setModal(`revisit:${c.id}`)}>I've been back <ArrowRight size={15}/></button></div></article>)}</div></>}
    {page==='blind'&&<><PageHeader kicker="NO MAP. NO DESTINATION." title="A blind walk" desc="Let the next small thing catch your attention. We’ll keep the prompts. You choose the way."/><div className="safety-banner"><ShieldCheck/><p><b>Blind Walk hides the destination, never the way home.</b><br/>Stay somewhere familiar and public. Your exit is always yours.</p></div><div className="blind-duration">{[15,30,45].map(d=><button key={d} onClick={()=>setDuration(d)} className={duration===d?'chosen':''}>{d}<small>minutes</small></button>)}</div><div className="blind-preview"><span className="eyebrow">THINGS TO NOTICE ALONG THE WAY</span><div className="prompt-list">{blindPrompts.slice(0,3).map((p,i)=><div key={p}><span>0{i+1}</span>{p}</div>)}</div><span className="eyebrow muted">A FEW PROMPTS. NO NEED TO FIND THEM ALL.</span></div><button className="button button-dark" onClick={()=>begin('blind',blindPrompts.slice(0,3).map((p,i)=>({title:`Notice ${i+1}`,description:p,category:'Observation',durationMinutes:duration})))}><Compass size={18}/> Start a blind walk <ArrowRight size={17}/></button></>}
    {page==='out'&&<><PageHeader kicker="NOTICE. NEVER RISK IT." title="Out of place" desc="A gentle record of things that do not belong in their surroundings." button="Record an observation" onClick={()=>setModal('out')}/><div className="safety-banner warning"><ShieldCheck/><p><b>Your safety comes first.</b><br/>Never touch unknown waste, sharp or chemical materials. Keep distance from suspicious objects, restricted places, and confrontation. No cleanup is worth a risk.</p></div><div className="out-list">{data.outOfPlace.length===0?<Empty icon={<Wind/>} title="Nothing noticed just yet." text="When something catches your eye, record it from a safe distance." action="Record an observation" onClick={()=>setModal('out')}/>:data.outOfPlace.map(o=><article className="out-row" key={o.id}>{o.photo&&<img src={o.photo}/>}<div><span className="eyebrow">{dateLabel(o.createdAt).toUpperCase()} · {o.status.toUpperCase()}</span><h3>{o.title}</h3><p>{o.note}</p></div><button className="icon-button" onClick={()=>set({...data,outOfPlace:data.outOfPlace.filter(x=>x.id!==o.id)})} aria-label="Delete observation"><Trash2 size={16}/></button></article>)}</div></>}
    {page==='impact'&&<><PageHeader kicker="A RECORD, NOT A SCORE" title="Your impact" desc="Only the things you actually did. Nothing estimated, awarded, or imagined."/><div className="impact-note"><span>✳</span><p>No streaks. No rankings. No pressure to make a number bigger.<br/><b>Just a little proof that you were here.</b></p></div><div className="impact-grid">{categories.map(([label,value])=><div className="impact-stat" key={label}><span>{value}</span><p>{label}</p></div>)}</div><div className="impact-caption"><Leaf size={17}/> Every number is counted from your own notes, on this device.</div></>}
    {page==='settings'&&<><PageHeader kicker="YOUR DATA, YOURS" title="Data & privacy" desc="Your notebook is stored in this browser. There is no account, no location tracking, and no shared feed."/><section className="privacy-section"><h2>What leaves this device</h2><p>If Gemma is configured, after you save a completed field note OBSERVE sends the note text, walk duration, quest titles, and expedition ID to the Gemma API. Photos and your previous notes are never sent. Google processes the request. Without Gemma credentials, a gentle deterministic reflection is used instead.</p><h2>Keep a copy</h2><p>Download your journal data as a JSON file for your own records.</p><button className="button button-outline" onClick={()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='observe-field-notes.json';a.click();URL.revokeObjectURL(a.href)}}><Download size={16}/> Export my data</button><h2>Start over</h2><p>Deleting your data clears your notes, capsules, and observations from this browser.</p><button className="button button-danger" onClick={()=>setModal('delete')}><Trash2 size={16}/> Delete all my data</button></section></>}</main>
  {modal&&<div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget)setModal('')}}><section className={`modal ${modal==='note-detail'?'note-modal':''}`} role="dialog" aria-modal="true"><button className="modal-close" onClick={()=>setModal('')} aria-label="Close"><X/></button>
    {modal==='note'&&data.pendingNote&&<><span className="eyebrow">WELCOME BACK · {data.pendingNote.duration} MINUTES OUTSIDE</span><h2>What did you notice?</h2><p className="modal-intro">Your words stay exactly as you write them. Add a little or a lot.</p><div className="note-prompts">{['What did you notice?','What surprised you?','What did you hear?','What did you normally overlook?'].map((q,i)=><label key={q}>{q}<textarea value={answers[`q${i}`]||''} onChange={e=>setAnswers({...answers,[`q${i}`]:e.target.value})} rows={i===0?3:2} placeholder={i===0?'Start wherever you like…':'Anything at all, or leave this blank.'}/></label>)}</div><div className="photo-upload"><label className="button button-outline">{photo?'Photo added':'Add an optional photo'}<input type="file" accept="image/*" onChange={e=>updatePhoto(e.target.files?.[0])} hidden/></label>{photo&&<button className="text-button" onClick={()=>setPhoto('')}>Remove</button>}<small>Please avoid photos of people without permission.</small></div><p className="gemma-disclosure"><Sparkles size={14}/> If Gemma is configured, this note text (not photos or past notes) is sent once for a short reflection.</p><button className="button button-dark full" disabled={saving} onClick={saveNote}>{saving?'Saving your page…':'Save field note'} <ArrowRight size={16}/></button></>}
    {modal==='capsule'&&<><span className="eyebrow">A NOTE FOR ANOTHER DAY</span><h2>Leave a time capsule.</h2><p className="modal-intro">Keep it broad. No precise location is saved.</p><label>Title<input value={capsuleDraft.title} onChange={e=>setCapsuleDraft({...capsuleDraft,title:e.target.value})} placeholder="The shady corner by the bakery"/></label><label>Your note<textarea rows={4} value={capsuleDraft.note} onChange={e=>setCapsuleDraft({...capsuleDraft,note:e.target.value})} placeholder="What would you like to remember?"/></label><label>Broad context <span className="optional">optional</span><input value={capsuleDraft.context} onChange={e=>setCapsuleDraft({...capsuleDraft,context:e.target.value})} placeholder="Along the canal, near the old market…"/></label><div className="photo-upload"><label className="button button-outline">{photo?'Photo added':'Add an optional photo'}<input type="file" accept="image/*" onChange={e=>updatePhoto(e.target.files?.[0])} hidden/></label>{photo&&<button className="text-button" onClick={()=>setPhoto('')}>Remove</button>}</div><button className="button button-dark full" onClick={saveCapsule}>Save for later <Bookmark size={16}/></button></>}
    {modal==='out'&&<><span className="eyebrow">A SAFE DISTANCE IS CLOSE ENOUGH</span><h2>What caught your eye?</h2><p className="modal-intro">Record it without a location. Never touch unknown or hazardous material.</p><label>What did you notice?<input value={outDraft.title} onChange={e=>setOutDraft({...outDraft,title:e.target.value})} placeholder="A plastic wrapper tangled in a hedge"/></label><label>A little context<textarea rows={3} value={outDraft.note} onChange={e=>setOutDraft({...outDraft,note:e.target.value})} placeholder="Anything you’d like to remember?"/></label><label>What happened?<select value={outDraft.status} onChange={e=>setOutDraft({...outDraft,status:e.target.value})}>{['Observed','Safely removed','Returned later','Reported','Not sure'].map(s=><option key={s}>{s}</option>)}</select></label>{(outDraft.status==='Safely removed')&&<p className="safety-inline"><ShieldCheck size={15}/> Only mark this if it was safe to handle. Never touch unknown waste.</p>}<div className="photo-upload"><label className="button button-outline">{photo?'Photo added':'Add an optional photo'}<input type="file" accept="image/*" onChange={e=>updatePhoto(e.target.files?.[0])} hidden/></label>{photo&&<button className="text-button" onClick={()=>setPhoto('')}>Remove</button>}<small>No people, exact locations, or risky close-ups.</small></div><button className="button button-dark full" onClick={saveOut}>Save observation <Check size={16}/></button></>}
    {modal==='delete'&&<><span className="eyebrow">A CLEAN PAGE</span><h2>Delete everything?</h2><p className="modal-intro">This permanently clears all field notes, capsules, and observations stored in this browser.</p><button className="button button-danger full" onClick={()=>{localStorage.removeItem('observe.v1');set(blankState);setModal('');setToast('Your local data was deleted.')}}><Trash2 size={16}/> Delete all data</button><button className="text-button cancel-button" onClick={()=>setModal('')}>Keep my notebook</button></>}
    {modal==='note-detail'&&selectedNote&&<><span className="eyebrow">FIELD NOTE · {dateLabel(selectedNote.createdAt).toUpperCase()}</span><h2>{selectedNote.quest[0]?.title||'A small observation'}</h2><div className="detail-meta">{selectedNote.duration} min outside · {selectedNote.quest.map(q=>q.category).join(', ')}</div>{selectedNote.photos[0]&&<img className="detail-photo" src={selectedNote.photos[0]}/>}<div className="note-answers">{Object.entries(selectedNote.answers).filter(([,v])=>v).map(([key,value])=><div key={key}><span className="eyebrow">{({q0:'WHAT DID YOU NOTICE?',q1:'WHAT SURPRISED YOU?',q2:'WHAT DID YOU HEAR?',q3:'WHAT DID YOU OVERLOOK?'} as Record<string,string>)[key]}</span><p>{value}</p></div>)}</div><div className="reflection"><Sparkles size={16}/><div><span className="eyebrow">A SMALL REFLECTION</span><p>{selectedNote.reflection}</p>{selectedNote.pattern&&<small>{selectedNote.pattern}</small>}</div></div><button className="button button-outline full" onClick={()=>setModal('share')}><Download size={16}/> Make a shareable card</button><p className="share-privacy">Your card includes no location or private information. Review before sharing.</p></>}
    {modal==='share'&&selectedNote&&<><span className="eyebrow">A PAGE FROM YOUR FIELD JOURNAL</span><h2>Share a small noticing.</h2><p className="modal-intro">A journal card with your observation and date. No location or impact stats.</p><div className="share-card-preview">{selectedNote.photos[0]&&<img src={selectedNote.photos[0]}/>}<div className="share-card-brand"><span className="brand-symbol"><Leaf size={15}/></span> OBSERVE <small>FIELD NOTES</small></div><span className="eyebrow">{dateLabel(selectedNote.createdAt).toUpperCase()}</span><h3>{selectedNote.quest[0]?.title||'A small observation'}</h3><blockquote>“{Object.values(selectedNote.answers).find(Boolean)||selectedNote.quest[0]?.description}”</blockquote><span className="share-card-footer">LOOK CLOSER. YOUR NEIGHBORHOOD IS ALIVE.</span></div><button className="button button-dark full" onClick={()=>downloadCard(selectedNote)}><Download size={16}/> Download field-note card (SVG)</button><p className="share-privacy">Review your note before sharing. Optional photo is included when you added one.</p></>}
    {modal.startsWith('revisit:')&&(()=>{const cap=data.capsules.find(c=>c.id===modal.slice(8));if(!cap)return null;return <><span className="eyebrow">YOU’VE BEEN HERE BEFORE</span><h2>{cap.title||'A place to remember'}</h2><div className="previous-note"><span className="eyebrow">LEFT {dateLabel(cap.createdAt).toUpperCase()}</span><p>{cap.note}</p></div><label>What changed this time?<textarea rows={4} value={revisitNote} onChange={e=>setRevisitNote(e.target.value)} placeholder="A new detail, a familiar one, or no change at all…"/></label><button className="button button-dark full" onClick={()=>addRevisit(cap)}>Add return visit <ArrowRight size={16}/></button></>})()}
  </section></div>}
  {toast&&<div className="toast"><Check size={16}/>{toast}</div>}
  </div>
}

function PageHeader({kicker,title,desc,button,onClick}:{kicker:string;title:string;desc:string;button?:string;onClick?:()=>void}){return <div className="page-header"><span className="eyebrow">{kicker}</span><h1>{title}</h1><p>{desc}</p>{button&&<button className="button button-dark" onClick={onClick}><Plus size={16}/>{button}</button>}</div>}
function Empty({icon,title,text,action,onClick}:{icon:React.ReactNode;title:string;text:string;action:string;onClick:()=>void}){return <div className="empty-state"><span className="empty-icon">{icon}</span><h2>{title}</h2><p>{text}</p><button className="button button-outline" onClick={onClick}>{action}<ArrowRight size={16}/></button></div>}
function makeShareCard(note:Note,quote:string){const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]!));const lines=quote.match(/.{1,44}(?:\s|$)/g)||[quote];const quoteSvg=lines.slice(0,5).map((line,i)=>`<tspan x="92" dy="${i===0?0:56}">${esc(line.trim())}</tspan>`).join('');const photo=note.photos[0]?`<image href="${note.photos[0]}" x="60" y="60" width="960" height="470" preserveAspectRatio="xMidYMid slice"/>`:'';const title=esc(note.quest[0]?.title||'A small observation');return `<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="1080" height="1350" viewBox="0 0 1080 1350"><rect width="1080" height="1350" rx="28" fill="#f5f4ee"/>${photo}<g transform="translate(76 ${photo?'580':'90'})"><circle cx="18" cy="18" r="18" fill="#dce6d8"/><path d="M15 29c-5-10 1-18 12-23 0 11-3 20-12 23zm-1-11 10 8" fill="none" stroke="#31513d" stroke-width="2"/><text x="49" y="24" font-family="Arial,sans-serif" font-size="27" font-weight="700" letter-spacing="3" fill="#252e28">OBSERVE</text><text x="0" y="115" font-family="monospace" font-size="18" letter-spacing="3" fill="#81887f">${esc(dateLabel(note.createdAt).toUpperCase())}</text><text x="0" y="205" font-family="Georgia,serif" font-size="50" fill="#34443a">${title}</text><path d="M0 244h900" stroke="#d9ded3"/><text x="0" y="300" font-family="monospace" font-size="16" letter-spacing="2" fill="#81887f">A THING I NOTICED</text><text x="0" y="370" font-family="Georgia,serif" font-size="34" font-style="italic" fill="#536453">“${quoteSvg}”</text><text x="0" y="610" font-family="monospace" font-size="14" letter-spacing="2" fill="#81887f">LOOK CLOSER. YOUR NEIGHBORHOOD IS ALIVE.</text><path d="M0 650h900" stroke="#d9ded3"/><circle cx="850" cy="750" r="82" fill="#e4eadf"/><path d="M837 782c-16-34 6-62 41-75-1 36-11 66-41 75zm-5-39 34 29" fill="none" stroke="#668069" stroke-width="5"/></g></svg>`}
